---
# tasks file for vcenter-vm
- import_tasks: auth.yml
- import_tasks: check_for_vm.yml
- import_tasks: provision_vm.yml
  when: context.tasks.provision
- import_tasks: power_off_vm.yml
  when: not context.tasks.provision
- import_tasks: delete_vm.yml
  when: not context.tasks.provision