# Setup build arguments with default versions
ARG TERRAFORM_VERSION=0.14.8

# Download Terraform binary
FROM debian:buster-slim as terraform
ARG TERRAFORM_VERSION
COPY hashicorp.asc hashicorp.asc
RUN  set -ex \
     && apt-get update \
     && apt-get install -y curl unzip gnupg

RUN set -ex \
    && curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS \
    && curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig \
    && gpg --import hashicorp.asc \
    && gpg --verify terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig terraform_${TERRAFORM_VERSION}_SHA256SUMS \
    && grep terraform_${TERRAFORM_VERSION}_linux_amd64.zip terraform_${TERRAFORM_VERSION}_SHA256SUMS | sha256sum -c - \
    && unzip -j terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Build final image
FROM debian:buster-slim
RUN set -ex \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    python3 \
    curl \
    jq \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && ln -s /usr/bin/python3 /usr/bin/python
COPY --from=terraform /terraform /usr/local/bin/terraform
WORKDIR /workspace
CMD ["bash"]
