ansible_host: "192.168.20.249"
device:
  hostname: "afm1.vin-lab.com"
  password: "{{vault_bigip_password}}"
  admin_user: "{{vault_adminUser}}"
  admin_pass: "{{vault_adminPass}}"
  management:
    ip: "192.168.20.249"
    gw: "192.168.20.254"
    ipmask: '192.168.20.249/24'
  do:
    devices:
      - template: "bigip_ha_ve_vmware"
        hostname: "afm-02-dev.vin-lab.com"
        dsc:
          primary: 
            host: "afm-01-dev.vin-lab.com"
            ip: "192.168.20.248"
          secondary: 
            host: "afm-02-dev.vin-lab.com"
            ip: "192.168.20.249"
        licenseKey:
        network:
          vlans:
            external:
              tag: 2
              interface: "1.1"
              selfipnf: "192.168.1.249/24"
              selfipf: "192.168.1.250/24"
              tagging: "{{'false'}}"
            server:
              tag: 4
              interface: "1.2"
              selfipnf: "192.168.3.249/24"
              selfipf: "192.168.3.250/24"
              tagging: "{{'false'}}"
            internal:
              tag: 1
              interface: "1.3"
              selfipnf: "192.168.2.249/24"
              selfipf: "192.168.2.250/24"
              tagging: "{{'false'}}"
            virtuals:
              tag: 10
              interface: "1.4"
              selfipnf: "192.168.10.249/24"
              selfipf: "192.168.10.250/24"
              tagging: "{{'false'}}"
            ha:
              tag: 40
              interface: "1.5"
              selfipnf: "192.168.4.249/24"
              tagging: "{{'false'}}"
          routes:
            default:
              gateway: "192.168.2.254"
            internal:
              network: "192.0.0.0/8"
              gateway: "192.168.1.254"
        dns:
          servers: "[\"192.168.2.251\",\"8.8.8.8\"]"
          search: "[\"vin-lab.com\"]"
        ntp:
          servers: "[\"0.pool.ntp.org\",\"1.pool.ntp.org\"]"
          timezone: "EST"
        # none,minimal,nominal,dedicated
        provisioning:
          avr: "nominal"
          ltm: "nominal"
          asm: "none"
          apm: "none"
          afm: "nominal"
  as3:
    apps:
      - name: "dmz_ingress"
        template: "afm_as3"
        ip: "192.168.1.250"
        port: 443
    irules: 
      pool_by_sni: |
            when CLIENTSSL_CLIENTHELLO {

            if { [SSL::extensions exists -type 0] } {

                ## if the servername exists - send to the appropriate pool
                ## you could also use a data group for this     

                set tls_servername [string range [SSL::extensions -type 0] 9 [string length [SSL::extensions -type 0]]]

                switch $tls_servername {
                    "vpn.vin-lab.com" { pool /firewall/external/vpn_pool }
                    "portal.vin-lab.com" { pool /firewall/external/portal_pool }
                    "betaportal.vin-lab.com" { pool /firewall/external/beta_portal_pool }
                    "social.vin-lab.com" { pool /firewall/external/social_pool }
                    "ontarget.vin-lab.com" { pool /firewall/external/ontarget_pool }
                    "bwapp.vin-lab.com" { pool /firewall/external/bwapp_pool }
                    "45.31.69.131" -
                    "" { pool /firewall/external/default_pool }
                    default { pool /firewall/external/default_pool }
                }

            }
            }
      internal_pool_by_sni: |
            when CLIENTSSL_CLIENTHELLO {

            if { [SSL::extensions exists -type 0] } {

                ## if the servername exists - send to the appropriate pool
                ## you could also use a data group for this     

                set tls_servername [string range [SSL::extensions -type 0] 9 [string length [SSL::extensions -type 0]]]

                switch $tls_servername {
                    "vpn.vin-lab.com" { pool /firewall/external/vpn_pool }
                    "portal.vin-lab.com" { pool /firewall/external/portal_pool }
                    "betaportal.vin-lab.com" { pool /firewall/external/beta_portal_pool }
                    "social.vin-lab.com" { pool /firewall/external/social_pool }
                    "ontarget.vin-lab.com" { pool /firewall/external/ontarget_pool }
                    "bwapp.vin-lab.com" { pool /firewall/external/bwapp_pool }
                    "45.31.69.131" -
                    "" { pool /firewall/external/default_pool }
                    default { pool /firewall/external/default_pool }
                }

            }
            }