- hosts: awx
  become: true

  vars:
    nodejs_version: "11.x"
    pip_install_packages:
      - name: docker-py
    awx_repo: https://github.com/ansible/awx.git
    awx_repo_dir: "~/awx"
    awx_version: devel
    awx_keep_updated: true
    ansible_distribution_major_version: "8"
  pre_tasks:
  - import_role:
      name: geerlingguy.repo-epel
  - name: add dependencies for centos8
    shell: |
      set -ex \
      && sudo dnf install  --enablerepo epel-playground  ansible -y \
      && sudo dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm -y \
      && sudo dnf install python3-pip -y \
      && sudo dnf module install nodejs -y \
      && ln -sf python3 /usr/bin/python \
      && ln -sf pip3 /usr/bin/pip \
      && pip install docker \
      && pip install docker-compose
  roles:
    # - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    # - geerlingguy.pip
    # - geerlingguy.nodejs
    - geerlingguy.awx