#https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-cluster-using-kubeadm-on-centos-7
# requires useraccount/centos/yourname
- hosts: k8s
  roles:
    - geerlingguy.docker
  vars: 
    ansible_distribution_major_version: "7"
    docker_package: docker-ce
- name: k8s-dependencies 
  import_playbook: k8s-dependencies.yaml
  vars: 
    k8s_version: "1.16.2"
- name: k8s-cluster setup
  import_playbook: k8s-setup.yaml 
  vars: 
    k8s_version: "1.16.2"
- name: k8s-test setup
  import_playbook: k8s-test.yaml