#https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-cluster-using-kubeadm-on-centos-7
# requires useraccount/centos/yourname
- hosts: k8s
  pre_tasks:
- name: k8s-dependencies 
  import_playbook: k8s-dependencies.yaml
  vars: 
    ansible_distribution_major_version: "8"
    docker_package: docker-ce
  # roles: 
  #   - geerlingguy.kubernetes
- name: k8s-master setup
  import_playbook: k8s-master.yaml
- name: k8s-workers setup
  import_playbook: k8s-workers.yaml
- name: k8s-test setup
  import_playbook: k8s-test.yaml
